// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBwEkUZc3aehNmC7W8_b7DV41A8mTLyOI',
    appId: '1:1040700578657:web:b236cbc27c9233563e0320',
    messagingSenderId: '1040700578657',
    projectId: 'hydrofarmtycoon',
    authDomain: 'hydrofarmtycoon.firebaseapp.com',
    storageBucket: 'hydrofarmtycoon.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhVFPFb99b1rilUEYXDmj_c1xbxpwU68U',
    appId: '1:1040700578657:android:0f21db48c78915d33e0320',
    messagingSenderId: '1040700578657',
    projectId: 'hydrofarmtycoon',
    storageBucket: 'hydrofarmtycoon.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLSSeYKeLXkatAyH8G0Ml64CxWcrstNv4',
    appId: '1:1040700578657:ios:7749aa6870b11e2f3e0320',
    messagingSenderId: '1040700578657',
    projectId: 'hydrofarmtycoon',
    storageBucket: 'hydrofarmtycoon.firebasestorage.app',
    iosBundleId: 'com.tuodominio.hydrofarmTycoon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLSSeYKeLXkatAyH8G0Ml64CxWcrstNv4',
    appId: '1:1040700578657:ios:7749aa6870b11e2f3e0320',
    messagingSenderId: '1040700578657',
    projectId: 'hydrofarmtycoon',
    storageBucket: 'hydrofarmtycoon.firebasestorage.app',
    iosBundleId: 'com.tuodominio.hydrofarmTycoon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBwEkUZc3aehNmC7W8_b7DV41A8mTLyOI',
    appId: '1:1040700578657:web:bbd7c223543161523e0320',
    messagingSenderId: '1040700578657',
    projectId: 'hydrofarmtycoon',
    authDomain: 'hydrofarmtycoon.firebaseapp.com',
    storageBucket: 'hydrofarmtycoon.firebasestorage.app',
  );
}
